### ISSUE TITLE
Use symlink instead of copy for easier distribution of config changes ?

### ISSUE THREAD

**Issue by PowerKiKi** [zfcampus/zf-development-mode#27]
Would there be any interest in a PR that would replace the file copy by a symlink instead ?

The obvious advantage is that it makes distribution of new development configuration much easier. As of now we have to git push the config, and then tell everybody to `./vendor/bin/zf-development-mode disable && ./vendor/bin/zf-development-mode enable`, which is both unintuitive and error prone.

If you think it would get merged, then I'll submit a PR for that.

**Comment by weierophinney** [comment]
This causes issues on Windows and IBM i Series, unfortunately, which is why we use the copy approach.

**Comment by PowerKiKi** [comment]
Symlink [are available in NTFS starting with Windows Vista](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365680(v=vs.85).aspx). And apparently also [available on IBM i Series](http://www-01.ibm.com/support/docview.wss?uid=nas8N1013397).

Would you please tell us more about what kind of issue there was ? I couldn't find anything

**Comment by PowerKiKi** [comment]
So what about enabling symlink only on whitelisted OS, such as Linux and macOS ? would you accept a PR for that ?

**Comment by webimpress** [comment]
@PowerKiKi If it is not a problem to you please create PR with this feature and then we all can see it and discuss it there. I'd like this functionality, it will be much nicer to have symlinks. Thanks!
